[build]
rustc = "toolchain/rustc.sh"
target = "aarch64-unknown-none-purecap"

[target.aarch64-unknown-none-purecap]
linker = "toolchain/ld.sh"
rustflags = ["-C", "target-feature=+strict-align"]
{%- if platform != "fvp" %}
runner = "./run-qemu.sh"
{%- endif %}

[net]
git-fetch-with-cli = true
